# Generated by Django 5.2.8 on 2026-03-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('add_refuel', 'Добавление заправки'), ('view_report', 'Просмотр отчёта'), ('access_denied', 'Отказ в доступе'), ('access_user_create', 'Создание пользователя доступа'), ('access_user_activate', 'Активация пользователя доступа'), ('access_user_deactivate', 'Деактивация пользователя доступа'), ('access_role_assign', 'Назначение роли доступа'), ('access_role_revoke', 'Снятие роли доступа'), ('access_scope_change', 'Изменение scope пользователя'), ('access_password_reset', 'Сброс пароля доступа'), ('error', 'Ошибка'), ('info', 'Информация')], max_length=50, verbose_name='Действие'),
        ),
    ]
