# Generated by Django 5.2.8 on 2026-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_telegramlinktoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fuelrecord',
            new_name='fuel_record_histori_648c11_idx',
            old_name='fuel_historic_reg_fill_idx',
        ),
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='core_system_created_3ea7c3_idx',
            old_name='syslog_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='systemlog',
            new_name='core_system_action_539f49_idx',
            old_name='syslog_action_created_idx',
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('add_refuel', 'Добавление заправки'), ('view_report', 'Просмотр отчёта'), ('access_denied', 'Отказ в доступе'), ('access_user_create', 'Создание пользователя доступа'), ('access_user_activate', 'Активация пользователя доступа'), ('access_user_deactivate', 'Деактивация пользователя доступа'), ('access_role_assign', 'Назначение роли доступа'), ('access_role_revoke', 'Снятие роли доступа'), ('access_scope_change', 'Изменение scope пользователя'), ('access_password_reset', 'Сброс пароля доступа'), ('telegram_link_code_issued', 'Выдан код привязки Telegram'), ('telegram_link_success', 'Telegram успешно привязан'), ('telegram_link_failed', 'Ошибка привязки Telegram'), ('error', 'Ошибка'), ('info', 'Информация')], max_length=50, verbose_name='Действие'),
        ),
    ]
