# Generated by Django 5.2.8 on 2026-03-26 09:09

from django.db import migrations, models


def forward_mark_caddy_tankers(apps, schema_editor):
    """Начальная пометка Volkswagen Caddy как топливозаправщиков (типовой кейс)."""
    Car = apps.get_model("core", "Car")
    Car.objects.filter(model__icontains="Caddy").update(is_fuel_tanker=True)


def reverse_noop(apps, schema_editor):
    """Обратная миграция не сбрасывает флаги — правки вручную в админке."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_fuelrecord_fuel_record_approve_99ad49_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_fuel_tanker',
            field=models.BooleanField(default=False, help_text='Отметка для авто, которые раздают топливо другим машинам. Используется в аналитике: общий топ по парку без них, отдельный график по заправщикам. Самообслуживание заправщика (карта/бот) остаётся обычными FuelRecord по этому же car_id.', verbose_name='Топливозаправщик'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['is_fuel_tanker'], name='cars_is_fuel_36a51a_idx'),
        ),
        migrations.RunPython(forward_mark_caddy_tankers, reverse_noop),
    ]
